# docker-compose.yml
version: '3'

networks:
  hnn:
    driver: bridge

volumes:
  hnn-database:


services:

  hnn-nginx:
    image: jimmg35/hnn-nginx:v0.230522.2
    container_name: hnn-nginx
    ports:
      - 9030:9030
    networks:
      - hnn
    depends_on:
      - hnn-client

  hnn-client:
    image: jimmg35/hnn-frontend-next:v0.0.9
    container_name: hnn-client
    networks:
      - hnn
    depends_on:
      - hnn-backend

  hnn-backend:
    image: jimmg35/hnn-backend-express:v0.230601.20
    container_name: hnn-backend
    entrypoint: [ "/app/entrypoints/entrypoint.sh" ]
    networks:
      - hnn
    volumes:
      - ./static:/app/src/static
    depends_on:
      - hnn-postgres

  hnn-postgres:
    image: postgis/postgis:14-3.3
    container_name: hnn-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DB_USER: ${POSTGRES_USERNAME}
      APP_DB_PASS: ${POSTGRES_PASSWORD}
      APP_DB_NAME: ${POSTGRES_DATABASE}
      PGDATA: /data/postgres
    volumes:
      - ./database-entrypoint:/docker-entrypoint-initdb.d/
      - hnn-database:/data/postgres
    networks:
      - hnn

  hnn-pgadmin:
    image: dpage/pgadmin4
    container_name: hnn-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN4_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN4_PASSWORD}
    ports:
      - "9031:80"
    networks:
      - hnn
