# docker-compose.yml
version: '3'

networks:
  hnn:
    driver: bridge

volumes:
  hnn-database:


services:

  hnn-nginx:
    image: hnn-nginx:dev
    build:
      context: ../hnn-nginx
      dockerfile: ../hnn-nginx/Dockerfile.dev
    container_name: hnn-nginx
    ports:
      - 9030:9030
    networks:
      - hnn
    depends_on:
      - hnn-frontend

  hnn-frontend:
    image: hnn-frontend-next:dev
    build:
      context: ../hnn-frontend-next
      dockerfile: ../hnn-frontend-next/Dockerfile.dev
    container_name: hnn-frontend
    ports:
      - 3001:3000
    volumes:
      - ../hnn-frontend-next:/app
    networks:
      - hnn
    depends_on:
      - hnn-backend

  hnn-backend:
    image: hnn-backend-express:dev
    build:
      context: ../hnn-backend-express
      dockerfile: ../hnn-backend-express/Dockerfile
    container_name: hnn-backend
    entrypoint: [ "/app/entrypoints/entrypoint.sh" ]
    networks:
      - hnn
    depends_on:
      - hnn-postgres

  hnn-postgres:
    image: postgis/postgis:14-3.3
    container_name: hnn-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DB_USER: ${POSTGRES_USERNAME}
      APP_DB_PASS: ${POSTGRES_PASSWORD}
      APP_DB_NAME: ${POSTGRES_DATABASE}
      PGDATA: /data/postgres
    volumes:
      - ./database-entrypoint:/docker-entrypoint-initdb.d/
      - hnn-database:/data/postgres
    networks:
      - hnn

  hnn-pgadmin:
    image: dpage/pgadmin4
    container_name: hnn-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN4_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN4_PASSWORD}
    ports:
      - "9031:80"
    networks:
      - hnn

  hnn-geoserver:
    image: docker.osgeo.org/geoserver:2.23.1
    container_name: hnn-geoserver
    ports:
      - "80:8080"
    environment:
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=wps,csw
      - EXTRA_JAVA_OPTS=-Xms1G -Xmx2G
    volumes:
      - ./geoserver/geoserver_data:/opt/geoserver_data/:Z
      - ./geoserver/additional_libs:/opt/additional_libs:Z # by mounting this we can install libs from host on startup
    networks:
      - hnn
