# docker-compose.yml
version: '3'

networks:
  hnn-db-dev:
    driver: bridge

volumes:
  hnn-database-dev:


services:

  hnn-postgres-dev:
    image: postgis/postgis:14-3.3
    container_name: hnn-postgres-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DB_USER: ${POSTGRES_USERNAME}
      APP_DB_PASS: ${POSTGRES_PASSWORD}
      APP_DB_NAME: ${POSTGRES_DATABASE}
      PGDATA: /data/postgres
    volumes:
      - ./database-entrypoint-dev:/docker-entrypoint-initdb.d/
      - hnn-database-dev:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - hnn-db-dev

  hnn-pgadmin-dev:
    image: dpage/pgadmin4
    container_name: hnn-pgadmin-dev
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN4_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN4_PASSWORD}
    ports:
      - "9031:80"
    networks:
      - hnn-db-dev

  hnn-geoserver-dev:
    image: docker.osgeo.org/geoserver:2.23.1
    container_name: hnn-geoserver-dev
    ports:
      - "80:8080"
    environment:
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=wps,csw
      - EXTRA_JAVA_OPTS=-Xms1G -Xmx2G
    volumes:
      - ./geoserver-dev/geoserver_data:/opt/geoserver_data/:Z
      - ./geoserver-dev/additional_libs:/opt/additional_libs:Z # by mounting this we can install libs from host on startup
    networks:
      - hnn-db-dev
