# docker-compose.yml
version: '3'

networks:
  hnn:
    driver: bridge

volumes:
  hnn-database:


services:

  hnn-postgres:
    image: postgis/postgis:14-3.3
    container_name: hnn-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DB_USER: ${POSTGRES_USERNAME}
      APP_DB_PASS: ${POSTGRES_PASSWORD}
      APP_DB_NAME: ${POSTGRES_DATABASE}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database-entrypoint:/docker-entrypoint-initdb.d/
      - hnn-database:/data/postgres
    networks:
      - hnn

  hnn-pgadmin:
    image: dpage/pgadmin4
    container_name: hnn-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN4_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN4_PASSWORD}
    ports:
      - "9031:80"
    networks:
      - hnn

  hnn-geoserver:
    image: docker.osgeo.org/geoserver:2.23.1
    container_name: hnn-geoserver
    ports:
      - "9032:8080"
    environment:
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=wps,csw
      - EXTRA_JAVA_OPTS=-Xms1G -Xmx2G
      - CORS_ENABLED=true
    volumes:
      - ./geoserver/geoserver_data:/opt/geoserver_data/:Z
      - ./geoserver/additional_libs:/opt/additional_libs:Z # by mounting this we can install libs from host on startup
    networks:
      - hnn
